### ISSUE TITLE
Add Today and Yesterday results

### ISSUE THREAD

**Issue by joshmedeski** [kudrykv/alfred-craftdocs-searchindex#11]
Can support for Today and Yesterday be added to the results?

This is how it looks in the Craft command popup

<img width="821" alt="Screen Shot 2022-06-29 at 6 17 45 PM" src="https://user-images.githubusercontent.com/2036594/176561515-4c47e4c4-46e7-4dcc-9c30-1cb9ce90347e.png">

**Comment by kudrykv** [comment]
Hello @joshmedeski!

This should be feasible.

I'm not using Alfred anymore, though. If you want to implement that, I could help you find places to update.

**Comment by joshmedeski** [comment]
@kudrykv what are you using now? Does that tool have Craft search integrated into it?

I'll take a closer look at how to add this myself, thanks.

**Comment by kudrykv** [comment]
@joshmedeski I'm using [Raycast](https://www.raycast.com/) now. It also [integrates with Craft](https://www.raycast.com/bgnfu7re/craftdocs).

**Comment by joshmedeski** [comment]
Cool, thanks. I see the Raycast integration doesn't support `Today` or `Yesterday` either ☹️

**Comment by joshmedeski** [comment]
Okay, so I got it working with the keywords "today" and "yesterday".

Here's how I did it.

Add a keyword input node on a workflow with "today" (with no argument). You can get the Craft icon by dragging the Craft application over the icon section of the input settings.

<img width="489" alt="Screen Shot 2022-07-05 at 11 17 30 AM" src="https://user-images.githubusercontent.com/2036594/177372693-ff1d22a9-915d-4be2-831e-cf9c67f8f942.png">

Connect the keyword to an open URL with the following value

```
craftdocs://openByQuery?query=today&spaceId={your-space-id}
```

**Note:** You can find `{your-space-id}` by copying a deep link on any Craft doc and pulling it from the `&spaceid` param.

Now, you can type "today" and this will pull up.

<img width="734" alt="Screen Shot 2022-07-05 at 11 15 58 AM" src="https://user-images.githubusercontent.com/2036594/177372574-1ee90185-326c-4858-b3aa-3a6567ce66c3.png">

Repeat the process by swapping `today` for `yesterday` in the `craftdocs://` URL to get yesterday.

Hope this helps someone else, I'm sure you can do something similar with Raycasts as well 😉

**Comment by kudrykv** [comment]
@joshmedeski it doesn't, but that's something I can implement there 🙂

If you will use Raycast someday and would need this in the future, you can ping me here, or somewhere near Raycast

**Comment by DFelten** [comment]
Today and yesterday would be great in Raycast as well :)

**Comment by kudrykv** [comment]
Haha
I'll look into it

**Comment by kudrykv** [comment]
@DFelten how do one format a link to today's document?

**Comment by DFelten** [comment]
> @DFelten how do one format a link to today's document?

Not sure what you mean exactly. 

If you want to link to the today note within a document you have to write `/today` or `yesterday`. iOS Shorcut detects the note also via Today and Yesterday.

**Comment by kudrykv** [comment]
@DFelten there should exist x-callback-url that links to different dates.

So, when I want to jump to today while I'm out of Craft (e.g., Raycast), I need to run smth like `open craft://query`. So, I'm searching how those URLs should look like 🙂

I've found something that suffices right away needs—[jumping to yesterday, today, and tomorrow](https://support.craft.do/hc/en-us/articles/360020168838-Using-URL-Scheme). I'm wondering, though, if Craft supports jumping to arbitrary dates.

**Comment by joshmedeski** [comment]
@kudrykv you can replace the query with a date in the `YYYY-MM-DD` format. I've confirmed this works.

```diff
-craftdocs://openByQuery?query=today&spaceId={your-id}
+craftdocs://openByQuery?query=2022-07-04&spaceId={your-id}
```

Hope that helps.

**Comment by kudrykv** [comment]
@joshmedeski that helps very much, thank you!

I'll now look into what would be a handy way of using it.

**Comment by kudrykv** [comment]
This is WIP

<img width="862" alt="CleanShot 2022-07-11 at 20 43 27@2x" src="https://user-images.githubusercontent.com/12697803/178325408-94e5cc11-b00b-47ff-8b27-c0789cbd9566.png">
<img width="862" alt="CleanShot 2022-07-11 at 20 43 46@2x" src="https://user-images.githubusercontent.com/12697803/178325420-1647492c-de8b-4d23-9255-d1698c421a10.png">

**Comment by kudrykv** [comment]
https://github.com/raycast/extensions/pull/2234
