### ISSUE TITLE
Search externals spaces?

### ISSUE THREAD

**Issue by mix579** [kudrykv/alfred-craftdocs-searchindex#12]
Hi, new user here. I don't use the default space in Craft at all because they don't offer end-to-end encryption. So all my documents are in External Spaces but I can't get this Alfred script to search them. It searches the local space just fine. Is there anything I'm missing?

**Comment by kudrykv** [comment]
Hi!
Huh, that's weird: Craft creates the index database for external spaces, too.

I don't have a subscription, though, to test it further.

**Comment by mix579** [comment]
Thanks for the response. It is strange—searches within Craft perform perfectly, changes from the Alfred plugin only show me results from the local space. It just adds to a list of things make me believe that Craft is not the solution I was looking for to replace Apple Notes.

**Comment by kudrykv** [comment]
There might be a bug here, or rather Craft extended its functionality while this workflow staled.

I'm not developing it anymore, as I've moved to [Raycast](https://www.raycast.com/) from Alftred. I'm going to continue reviewing incoming changes if there would be any ¯\_(ツ)_/¯
There is an analogous extension in Raycast, but I suspect it would have the same issue.

What issue do you have with Apple Notes that you're looking for alternatives to?

**Comment by mafredri** [comment]
@mix579 I could look into it if you can share more about your setup, however, I can't reproduce your issue. Works fine for me (using external location):

<img width="597" alt="image" src="https://user-images.githubusercontent.com/147409/182798711-08f3306d-f2dc-42c8-8761-f51ced92bf50.png">

~~PS. If you're using an M1 Mac, you might try to build the project yourself (not using the amd64 release), not sure why that would help but that's the only difference between our setups I can think of.~~ Edit: Just realized both are published so never mind that. 😅

**Comment by mix579** [comment]
> What issue do you have with Apple Notes that you're looking for alternatives to?

I actually like Apple Notes quite a bit, however, I'd like to see native Markdown support, for input but even more so for export. I've tried various Shortcuts for rich text to markdown conversion but they all produced shall we say sub-optimal Markdown output. The other issue I ran into it that if I edit an embedded file (specifically Excel), while changes in the rest of the note get propagated to other devices, the embedded file does not. I have looked at other note taking apps as well (Obsidian, Bear, etc) but none resonated with me.

**Comment by mix579** [comment]
Mystery solved! Operator error… 😢

When I tried to reply to @mafredri's offer for help, I grabbed the version information for OS, Craft, etc, and then realized that for some reason I don't know my version of the plugin was 0.1.2, not the latest 0.4.

I installed the new one, and now searches work perfectly! Thank you, guys.
