### ISSUE TITLE
Create file / or when no documents matched

### ISSUE THREAD

**Issue by h-jia** [kudrykv/alfred-craftdocs-searchindex#2]
Hi, thanks for this great workflow! Is it possible to add a function that allows creating a new file or when no documents are matched?

Similar to bn [alfred-bear](https://github.com/chrisbro/alfred-bear)

Thanks!

**Comment by kudrykv** [comment]
Hi!
Hm. Yeah, that should be possible.

**Comment by mafredri** [comment]
Would it make sense to always present the option to create (unless there's an exact match), similar to the Craft built-in search?

<img width="524" alt="image" src="https://user-images.githubusercontent.com/147409/150684474-b133bae5-4d02-441e-aeff-7d6688b39c89.png">

If not, perhaps it would make sense to have a separate keyword `cn(ew)` or `cc(reate)` so it's always possible to create a new document (even when there would be matches)?
